### ISSUE TITLE
Review "I want to..." options on front page 

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/new-website#31]
### How could the content be improved?

@sheraaronhurt You had suggested the following items for the "I want to" menu on the front page:

- See upcoming/past workshops
- Request a workshop
- See the curriculum

Please test it out to see how it works.  
This has been implemented with the following notes:
- Only have upcoming workshops (you can go to past workshops from there)
- Request a workshop goes directly to the AMY form.  Would you prefer it goes to The Carpentries website workshops page? 

### Which part of the content does your suggestion apply to?

https://dc-new-website.netlify.app/

**Comment by maneesha** [comment]
@sheraaronhurt The same thing is being set up on all three lesson program sites. You can note here if it all looks good or share any comments.

**Comment by sheraaronhurt** [comment]
@maneesha all 3 pages LGTM! I like that it takes them directly to the AMY page.
