### ISSUE TITLE
Review frontpage image & text

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/new-website#33]
Review image and text on the front page.
Our options for text color are black or white.  Should we consider images that would make a good background for that text?

**Comment by OscarSiba** [comment]
To what page is this referring to @maneesha? Or is it all pages/areas where there's an image?

**Comment by maneesha** [comment]
The image on the front page is what you see here, that shows four computer monitors and part of someone's hand: https://dc-new-website.netlify.app/
The text on the frontpage is the text on that page that reads "Data Carpentry is a lesson program within The Carpentries building communities teaching universal data skills."

**Comment by OscarSiba** [comment]
Please replace this image with the image titled alvaro-reyes-LXx1hwmp67E-unsplash.jpg (first choice) or 
alvaro-reyes-fSWOVc3e06w-unsplash (second choice) in the [website images folder](https://drive.google.com/drive/folders/1Vz0H75cLMvx-pdmi57ZQDuip_fOb6S_A), depending on which has better contrast with the white text.
