### ISSUE TITLE
Footer description text

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/new-website#34]
We have placeholder language in the footer.

> Data Carpentry is a lesson program of The Carpentries. Cake pastry candy carrot cake croissant tootsie roll chocolate bar dragée cotton candy.

What language should actually go there?

**Comment by OscarSiba** [comment]
For all the lesson program sites footer please simply use, "[xxx] Carpentry is a lesson program of The Carpentries."

**Comment by maneesha** [comment]
Fixed with #45
