### ISSUE TITLE
Footer menus & socials

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/new-website#35]
Should the footer menus & socials on the lesson program sites be the same as on The Carpentries site? 

@OscarSiba if they should be the same throughout, please just let me know here.  If you would like to see different footer menus & socials on each LP site, please open an issue on each LP new website repo.

**Comment by OscarSiba** [comment]
They should be the same everywhere, thank you @maneesha.

**Comment by maneesha** [comment]
Assigning back to me to implement

**Comment by maneesha** [comment]
Footer menus have been updated. Footers are exactly the same across all four websites. Please review. Close this issue if this looks good, or share any feedback here.
