### ISSUE TITLE
Review lessons page

### ISSUE THREAD

**Issue by maneesha** [datacarpentry/new-website#42]
Review lessons page: https://dc-new-website.netlify.app/lessons/

Content has been copied & pasted over from current lessons page.

**Comment by tobyhodges** [comment]
In my view, the whole "Materials in Early Development" section can be removed, including the table for the economics curriculum. Tagging @ErinBecker so that she is aware. Everything else looks good to me.

**Comment by maneesha** [comment]
@tobyhodges I've made the change. You can review here: https://dc-new-website.netlify.app/lessons/

Close this issue if it looks good now, or please share any other feedback.

**Comment by tobyhodges** [comment]
Thanks @maneesha
