### ISSUE TITLE
Style changes to DC website pages

### ISSUE THREAD

**Issue by OscarSiba** [datacarpentry/new-website#50]
### How could the content be improved?

**About us page**: https://dc-new-website.netlify.app/about-us/
- [x] Please also add the "Subscribe to our newsletter" button here. 
- [x] On the third paragraph, please hyperlink "since 2014" to this link: https://carp-new-website.netlify.app/about-us/#our-history

**Governance page**: https://dc-new-website.netlify.app/about-us/governance/
- [x] Remove the "Table of contents" on the side bar menu.

**Data Carpentry Lessons**: https://dc-new-website.netlify.app/lessons/
- [x] In the second paragraph of the intro text please spell "organized" with an "s".
- [x] In the third paragraph, please hyperlink reference to the Carpentries Handbook.

**Comment by maneesha** [comment]
Addressed with #51
